import { useState, useEffect } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { ArrowLeft, FileText, Share2, Download, Phone, MapPin, Home, Palette } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export default function ProjectSummaryScreen() {
  const navigate = useNavigate();
  const { projectId } = useParams();
  const { toast } = useToast();
  const [projectData, setProjectData] = useState<any>(null);
  const [rooms, setRooms] = useState<any[]>([]);
  const [estimation, setEstimation] = useState<any>(null);

  useEffect(() => {
    // Load all project data
    const project = localStorage.getItem(`project_${projectId}`);
    const roomData = localStorage.getItem(`rooms_${projectId}`);
    const estimationData = localStorage.getItem(`estimation_${projectId}`);

    if (project) setProjectData(JSON.parse(project));
    if (roomData) setRooms(JSON.parse(roomData));
    if (estimationData) setEstimation(JSON.parse(estimationData));
  }, [projectId]);

  const totalAreas = rooms.reduce(
    (acc, room) => ({
      floorArea: acc.floorArea + room.floorArea,
      wallArea: acc.wallArea + room.wallArea,
      ceilingArea: acc.ceilingArea + room.ceilingArea
    }),
    { floorArea: 0, wallArea: 0, ceilingArea: 0 }
  );

  const handleExportPDF = () => {
    toast({
      title: "PDF Export",
      description: "Project summary exported as PDF successfully!",
    });
  };

  const handleExportExcel = () => {
    toast({
      title: "Excel Export",
      description: "Project data exported to Excel successfully!",
    });
  };

  const estimationDetails = estimation?.estimation || estimation || {};
  
  const handleShareWhatsApp = () => {
    const message = `ECA Pro Project Summary\n\nCustomer: ${projectData?.customerName}\nTotal Area: ${totalAreas.wallArea.toFixed(1)} sq.ft\nEstimated Cost: ₹${estimationDetails?.totalCost?.toLocaleString() || 'N/A'}\n\nGenerated by Asian Paints ECA Pro`;
    const url = `https://wa.me/?text=${encodeURIComponent(message)}`;
    window.open(url, '_blank');
  };

  const handleShareEmail = () => {
    const subject = `Project Summary - ${projectData?.customerName}`;
    const body = `Please find attached the project summary for ${projectData?.customerName}.\n\nTotal Area: ${totalAreas.wallArea.toFixed(1)} sq.ft\nEstimated Cost: ₹${estimationDetails?.totalCost?.toLocaleString() || 'N/A'}\n\nGenerated by Asian Paints ECA Pro`;
    const url = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;
    window.open(url);
  };

  if (!projectData || !estimation) {
    return (
      <div className="min-h-screen bg-background flex items-center justify-center">
        <div className="text-center">
          <h2 className="text-xl font-semibold mb-2">Loading Project Summary...</h2>
          <p className="text-muted-foreground">Please wait while we prepare your summary.</p>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="eca-gradient text-white p-4">
        <div className="flex items-center space-x-3">
          <Button 
            variant="ghost" 
            size="icon"
            className="text-white hover:bg-white/20"
            onClick={() => navigate(`/paint-estimation/${projectId}`)}
          >
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div>
            <h1 className="text-xl font-semibold">Project Summary</h1>
            <p className="text-white/80 text-sm">Complete project overview</p>
          </div>
        </div>
      </div>

      <div className="p-4 space-y-6">
        {/* Customer Information */}
        <Card className="eca-shadow">
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <Home className="mr-2 h-5 w-5 text-primary" />
              Customer Details
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="flex items-center">
              <div className="w-6 h-6 bg-primary/10 rounded-full flex items-center justify-center mr-3">
                <div className="w-2 h-2 bg-primary rounded-full"></div>
              </div>
              <div>
                <p className="font-semibold text-foreground">{projectData.customerName}</p>
                <p className="text-sm text-muted-foreground">Customer Name</p>
              </div>
            </div>
            <div className="flex items-center">
              <Phone className="h-4 w-4 text-muted-foreground mr-3 ml-1" />
              <div>
                <p className="font-medium text-foreground">{projectData.mobile}</p>
                <p className="text-sm text-muted-foreground">Mobile Number</p>
              </div>
            </div>
            <div className="flex items-start">
              <MapPin className="h-4 w-4 text-muted-foreground mr-3 ml-1 mt-1" />
              <div>
                <p className="font-medium text-foreground">{projectData.address}</p>
                <p className="text-sm text-muted-foreground">Address</p>
              </div>
            </div>
            <div className="flex items-center">
              <Badge variant="outline" className="bg-accent">
                {projectData.projectType} Project
              </Badge>
            </div>
          </CardContent>
        </Card>

        {/* Room Summary */}
        <Card className="eca-shadow">
          <CardHeader>
            <CardTitle className="text-lg">Room Measurements</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="space-y-3">
              {rooms.map((room, index) => (
                <div key={room.id} className="flex justify-between items-center p-3 bg-muted rounded-lg">
                  <div>
                    <p className="font-medium text-foreground">{room.name}</p>
                    <p className="text-sm text-muted-foreground">
                      {room.length}' × {room.width}' × {room.height}'
                    </p>
                  </div>
                  <div className="text-right">
                    <p className="font-semibold text-foreground">{room.wallArea.toFixed(1)} sq.ft</p>
                    <p className="text-xs text-muted-foreground">Wall Area</p>
                  </div>
                </div>
              ))}
            </div>

            <div className="mt-4 p-4 eca-gradient text-white rounded-lg">
              <div className="grid grid-cols-3 gap-4 text-center">
                <div>
                  <p className="text-white/80 text-sm">Total Floor</p>
                  <p className="text-xl font-bold">{totalAreas.floorArea.toFixed(1)}</p>
                  <p className="text-white/80 text-xs">sq.ft</p>
                </div>
                <div>
                  <p className="text-white/80 text-sm">Total Wall</p>
                  <p className="text-xl font-bold">{totalAreas.wallArea.toFixed(1)}</p>
                  <p className="text-white/80 text-xs">sq.ft</p>
                </div>
                <div>
                  <p className="text-white/80 text-sm">Total Ceiling</p>
                  <p className="text-xl font-bold">{totalAreas.ceilingArea.toFixed(1)}</p>
                  <p className="text-white/80 text-xs">sq.ft</p>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>

        {/* Paint & Cost Summary */}
        <Card className="eca-shadow">
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <Palette className="mr-2 h-5 w-5 text-secondary" />
              Paint & Cost Details
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="bg-muted rounded-lg p-4">
              <div className="flex justify-between items-center mb-2">
                <span className="text-sm text-muted-foreground">Selected Product:</span>
                <Badge variant="outline">{estimation?.product?.category || 'N/A'}</Badge>
              </div>
              <p className="font-semibold text-foreground text-lg">{estimation?.product?.name || 'No product selected'}</p>
              <p className="text-sm text-muted-foreground">{estimation?.paintType || 'N/A'} Paint</p>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="text-center p-4 border border-border rounded-lg">
                <p className="text-sm text-muted-foreground">Paint Required</p>
                <p className="text-2xl font-bold text-foreground">{estimationDetails?.litersRequired || 'N/A'}</p>
                <p className="text-xs text-muted-foreground">Liters (2 coats)</p>
              </div>
              <div className="text-center p-4 border border-border rounded-lg">
                <p className="text-sm text-muted-foreground">Area Coverage</p>
                <p className="text-2xl font-bold text-foreground">{estimationDetails?.area ? estimationDetails.area.toFixed(1) : 'N/A'}</p>
                <p className="text-xs text-muted-foreground">sq.ft</p>
              </div>
            </div>

            <div className="bg-primary/10 border border-primary/20 rounded-lg p-4 text-center">
              <p className="text-sm text-primary font-medium">Estimated Total Cost</p>
              <p className="text-3xl font-bold text-primary">₹{estimationDetails?.totalCost ? estimationDetails.totalCost.toLocaleString() : 'N/A'}</p>
              <p className="text-xs text-primary/70">Including material cost</p>
            </div>
          </CardContent>
        </Card>

        {/* Export & Share Options */}
        <Card className="eca-shadow">
          <CardHeader>
            <CardTitle className="flex items-center text-lg">
              <Share2 className="mr-2 h-5 w-5 text-accent-foreground" />
              Export & Share
            </CardTitle>
          </CardHeader>
          <CardContent className="space-y-3">
            <div className="grid grid-cols-2 gap-3">
              <Button variant="outline" onClick={handleExportPDF} className="h-12">
                <FileText className="mr-2 h-4 w-4" />
                Export PDF
              </Button>
              <Button variant="outline" onClick={handleExportExcel} className="h-12">
                <Download className="mr-2 h-4 w-4" />
                Export Excel
              </Button>
            </div>
            <div className="grid grid-cols-2 gap-3">
              <Button onClick={handleShareWhatsApp} className="h-12 bg-green-600 hover:bg-green-700">
                Share WhatsApp
              </Button>
              <Button variant="secondary" onClick={handleShareEmail} className="h-12">
                Share Email
              </Button>
            </div>
          </CardContent>
        </Card>

        {/* Action Buttons */}
        <div className="grid grid-cols-2 gap-3">
          <Button 
            variant="outline" 
            onClick={() => navigate("/dashboard")}
            className="h-12"
          >
            Back to Dashboard
          </Button>
          <Button 
            onClick={() => navigate("/add-project")}
            className="h-12"
          >
            New Project
          </Button>
        </div>
      </div>

      <div className="h-6"></div>
    </div>
  );
}